name: Build and deploy Node.js project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to the function app project
  NODE_VERSION: '20.x' # Node.js version
  FUNCTION_APP_NAME: 'skydive-two' # Set to the desired Function App name (e.g., skydive-two or third-function-app)

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies Using Npm
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Rename function file to match Function App name
        shell: pwsh
        run: |
          if (Test-Path "thirdFunctionApp.js") {
            Move-Item -Path "thirdFunctionApp.js" -Destination "${{ env.FUNCTION_APP_NAME }}.js"
          }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT for Azure login
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Checkout repository for ARM template
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_379032813E7C4214B310838B21A2F70F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7732A1EB8B39466E96665CEEA2821818 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD8FBCFB28FB4F3CB13FA69233A0A55A }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: 'first-function-app-resource-grp'
          template: 'infra/azure-function-app.json'
          parameters: 'infra/azure-function-app.parameters.json sites_third_function_app_name=${{ env.FUNCTION_APP_NAME }}'
          deploymentName: 'Deploy-Function-App-${{ github.run_id }}'

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}